language: java
jdk:
  - openjdk14
sudo: required
services:
  - docker
script:
  #- cd notes-fe
  - docker build -t bbelovic/notes-fe:latest notes-fe/
    #- cd ..
  - mvn -f notes-be/pom.xml clean compile jib:dockerBuild
   
  #after_success:
  
