language: java
jdk:
 - openjdk14
sudo: required
services:
 - docker
script:
 - mvn -f notes-be/pom.xml clean compile jib:dockerBuild
after_success: 
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
 - docker push bbelovic/notes-app
 - echo "$HEROKU_REGISTRY_PASSWORD" | docker login -u "$HEROKU_REGISTRY_USERNAME" --password-stdin
 - docker push bbelovic/notes-app


