language: java
jdk:
  - openjdk14
sudo: required
services:
  - docker
script:
  docker build -t bbelovic/notes-fe:latest notes-fe
  cd notes-be && mvn clean compile jib:dockerBuild
   
  #after_success:
  
