language: java
jdk:
  - openjdk14
sudo: required
services:
  - docker
script:
  - docker build -t bbelovic/notes-fe:latest notes-fe
  - mvn -f notes-fe/pom.xml clean compile jib:dockerBuild
   
  #after_success:
  
