version: '3'
services:
  db:
    image: 'postgres:9.6'
    environment:
      - POSTGRES_USER=notes_user
      - POSTGRES_PASSWORD=notes_pass
      - POSTGRES_DB=notes_db
  notes-be:
    image: 'notes-be-jib:latest'
    environment:
      - DB_USER=notes_user
      - DB_PASSWD=notes_pass
      - DB_NAME=notes_db
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db
    entrypoint: ["./entrypoint.sh"]
    command: ["db:5432"]
        #    command: ["./wait-for-it.sh", "db:5432", "--timeout=15"]
